<?php
namespace Reactor\Database\Migrations;

use Reactor\Contracts\DatabaseManagerInterface;
use Reactor\Contracts\LoggerInterface;

/**
 * Executes migrations (run, rollback, reset, refresh).
 *
 * Schema transactions are only wrapped when the active driver supports
 * transactional DDL. MySQL, MariaDB, SQL Server and Oracle implicitly
 * commit every DDL statement, which causes PDO::commit() to fail with
 * "There is no active transaction" once the driver has auto-committed
 * the transaction opened by PDO::beginTransaction().
 *
 * Drivers known to support transactional DDL (PostgreSQL, SQLite) keep
 * the original behaviour where up()/down() and the tracking insert are
 * committed atomically.
 */
class MigrationRunner
{
    /**
     * Drivers that do NOT support transactional DDL.
     *
     * These engines auto-commit DDL statements (ALTER TABLE, CREATE
     * TABLE, DROP TABLE, ...), which breaks PDO's transaction state
     * machine and makes commit()/rollBack() throw.
     *
     * @var array<int, string>
     */
    private const NON_TRANSACTIONAL_DDL_DRIVERS = [
        'mysql',
        'mariadb',
        'sqlsrv',
        'oracle',
    ];

    private DatabaseManagerInterface $db;
    private LoggerInterface $logger;
    private MigrationRepository $repository;

    public function __construct(DatabaseManagerInterface $db, LoggerInterface $logger, MigrationRepository $repository)
    {
        $this->db = $db;
        $this->logger = $logger;
        $this->repository = $repository;
    }

    public function run(): void
    {
        $pending = $this->repository->getPendingMigrations();
        if (empty($pending)) {
            $this->logger->info('No pending migrations');
            return;
        }

        $batch = $this->repository->getNextBatchNumber();
        foreach ($pending as $name => $file) {
            $this->runMigration($name, $batch);
        }
        $this->logger->info('Migrations completed: ' . count($pending) . ' executed');
    }

    private function runMigration(string $name, int $batch): void
    {
        $instance = $this->repository->loadMigration($name);

        if ($this->supportsSchemaTransactions()) {
            $this->db->transaction(function () use ($instance, $name, $batch) {
                $instance->up();
                $this->repository->markRan($name, $batch);
            });
        } else {
            // The active driver auto-commits DDL, so wrapping up() in a
            // transaction would make PDO::commit() throw "There is no
            // active transaction". Run the schema change directly and
            // then record it. If up() succeeds but the insert fails,
            // the migration runs again on the next attempt; migration
            // stubs generated by MigrateMakeCommand are idempotent
            // (they use hasTable / dropIfExists guards).
            $instance->up();
            $this->repository->markRan($name, $batch);
        }

        $this->logger->info("Migration executed: $name");
    }

    public function rollback(int $steps = 1): void
    {
        $batches = $this->repository->getBatches($steps);
        if (empty($batches)) {
            $this->logger->info('Nothing to rollback');
            return;
        }

        foreach ($batches as $batch) {
            $this->rollbackBatch((int) $batch);
        }
    }

    private function rollbackBatch(int $batch): void
    {
        $migrations = $this->repository->getMigrationsByBatch($batch);
        foreach ($migrations as $migration) {
            $this->rollbackMigration($migration->migration);
            $this->repository->remove($migration->migration);
        }
        $this->logger->info("Rolled back batch: $batch");
    }

    private function rollbackMigration(string $name): void
    {
        $instance = $this->repository->loadMigration($name);

        if ($this->supportsSchemaTransactions()) {
            $this->db->transaction(function () use ($instance) {
                $instance->down();
            });
        } else {
            $instance->down();
        }

        $this->logger->info("Rolled back: $name");
    }

    public function reset(): void
    {
        $batches = $this->repository->getBatches(PHP_INT_MAX);
        if (empty($batches)) {
            $this->logger->info('Nothing to reset');
            return;
        }

        foreach ($batches as $batch) {
            $this->rollbackBatch((int) $batch);
        }
    }

    public function refresh(): void
    {
        $this->reset();
        $this->run();
    }

    /**
     * Whether the active database driver supports transactional DDL.
     *
     * PostgreSQL and SQLite roll back DDL together with DML, so wrapping
     * up()/down() in a transaction is safe. MySQL, MariaDB, SQL Server
     * and Oracle auto-commit every DDL statement, which breaks PDO's
     * transaction state machine.
     *
     * The driver name is read from the database manager's config so the
     * check also works for applications that route through a custom
     * DatabaseManagerInterface implementation instead of Eloquent.
     */
    private function supportsSchemaTransactions(): bool
    {
        $driver = $this->db->getConfig()['driver'] ?? 'sqlite';
        return !in_array(strtolower((string) $driver), self::NON_TRANSACTIONAL_DDL_DRIVERS, true);
    }
}
